checker:
  # Amount of checks for a account many times to check a account.
  # Needs to be 1 or higher
  retries: 3

  # Higher for better accuracy but slower (counted in milliseconds)
  timeout: 15000

  # Threads for account checking
  threads: 100

  # Check hits if its a mail access
  mail_access: true
  
  # Save ranked accounts in secured.txt or unsecured.txt
  save_rankedtypes: true
  
  # Save bad accounts, good for checking paid alts (will use more cpu and take longer)
  save_bad: false

  # User should keep this false
  debugging: false
  
  # Api key to check hypixel ranks and levels
  # use any key from the following
  # 79326ca4-54b2-4a8a-a5b4-d9ee111f674b
  # 99ad5c56-5320-4b0c-9e4f-a7af1c9641f9
  # 0f649707-2603-4fd8-853e-8c80ae93e3a9
  # cdfa2b06-d2c9-4525-9154-2b204d6b4f0b
  # 01c39cd8-dffc-4ce4-8faf-5069bc9d06ba
  # 0c723844-5762-4366-9034-3be21758b685
  hypixel_api_key: '79326ca4-54b2-4a8a-a5b4-d9ee111f674b'

  capes:
    # Check capes
    liquidbounce: true
    optifine: true
    labymod:  true
    # Minecon/Mojang cape
    minecon:  true

  rank:
    mineplex: true
    hypixel:  true
    hivemc: true

  level:
    # Check Levels
    hypixel: true
    mineplex: true
    # Minimum high level accounts
    hypixel_level: 25
    mineplex_level: 25

  proxy:
    # If proxies should be used, Will be proxyless if set to false (Use VPN if set to false or you will be ip banned)
    proxy: true
    # Proxy types: https | socks4 | socks5
    proxy_type: 'https'
    # Proxy file name
    proxy_file: 'proxies.txt'
